export const SET_STATIONS = "SET_STATIONS";
export const SET_STATION = "SET_STATION";
export const SET_STATIONS_NORTHZONE = "SET_STATIONS_NORTHZONE";
export const SET_STATIONS_CENTERZONE = "SET_STATIONS_CENTERZONE";
export const SET_STATIONS_SOUTHZONE = "SET_STATIONS_SOUTHZONE";
